export const stations = [
  {
    id: 'dorojnoe',
    title: 'Дорожное Радио',
    range: '87.5',
    stream: 'http://dorognoe.hostingradio.ru:8000/dorognoe',
    image: './logos/dorojnoe.jpg',
  },
  {
    id: 'retro',
    title: 'Ретро FM',
    range: '88.0',
    stream: 'http://emgspb.hostingradio.ru/retrofmspb128.mp3',
    image: './logos/retro.jpg',
  },
  {
    id: 'svoboda',
    title: 'Радио свобода',
    range: '88.5',
    stream: 'http://rfe04.akacast.akamaistream.net/7/509/437762/v1/ibb.akacast.akamaistream.net/rfe04',
    image: './logos/svoboda.jpg',
  },
  {
    id: 'umor',
    title: 'Юмор FM',
    range: '88.9',
    stream: 'http://stream06.media.rambler.ru:80/umor128.mp3',
    image: './logos/umor.jpg',
  },
  {
    id: 'ermitage',
    title: 'Радио Эрмитаж',
    range: '90.1',
    stream: 'http://91.190.117.131:8000/live',
    image: './logos/ermitage.jpg',
  },
  {
    id: 'eho',
    title: 'Эхо Москвы',
    range: '91.2',
    stream: 'http://81.19.85.197/echo.mp3',
    image: './logos/eho.jpg',
  },
  {
    id: 'karnaval',
    title: 'Радио Карнавал',
    range: '92.8',
    stream: 'http://stream02.media.rambler.ru:80/karnaval128.mp3',
    image: './logos/karnaval.jpg',
  },
  {
    id: 'love',
    title: 'Love Radio',
    range: '96.7',
    stream: 'http://stream.variant.fm:8000/LOVE-192',
    image: './logos/love.jpg',
  },
  {
    id: 'nostalgia',
    title: 'Ностальгия FM',
    range: '98.6',
    stream: 'http://93.189.147.117:8000/nostalgiafm.mp3',
    image: './logos/nostalgia.jpg',
  },
  {
    id: 'rossii',
    title: 'Радио России',
    range: '99.0',
    stream: 'http://icecast.vgtrk.cdnvideo.ru/rrzonam_mp3_192kbps',
    image: './logos/russland.jpg',
  },
  {
    id: 'europa',
    title: 'Европа Плюс',
    range: '100.5',
    stream: 'http://emgspb.hostingradio.ru/europaplusspb128.mp3',
    image: './logos/europa.jpg',
  },
  {
    id: 'eldo',
    title: 'Эльдорадио',
    range: '101.4',
    stream: 'http://emgspb.hostingradio.ru/eldoradio128.mp3',
    image: './logos/eldo.jpg',
  },
  {
    id: 'detskoe',
    title: 'Детское радио',
    range: '103.7',
    stream: 'http://ic2.101.ru:8000/v14_1',
    image: './logos/detskoe.jpg',
  },
  {
    id: 'nashe',
    title: 'Наше радио',
    range: '104.0',
    stream: 'http://nashe1.hostingradio.ru/nashespb128.mp3',
    image: './logos/nashe.jpg',
  },
  {
    id: 'russkoe',
    title: 'Русское радио',
    range: '105.3',
    stream: 'http://icecast.russkoeradio.cdnvideo.ru:8000/rr_m.aac',
    image: './logos/russkoe.jpg',
  },
  {
    id: 'rekord',
    title: 'Радио Рекорд',
    range: '106.3',
    stream: 'http://air.radiorecord.ru:8101/rr_320.m3u',
    image: './logos/rekord.jpg',
  },
  {
    id: 'mayak',
    title: 'Радио  Маяк',
    range: '107.0',
    stream: 'https://icecast-vgtrk.cdnvideo.ru/mayakfm_aac_64kbps',
    image: './logos/mayak.jpg',
  },
  {
    id: 'biznesfm',
    title: 'Бизнес FM',
    range: '107.4',
    stream: 'http://stream02.media.rambler.ru/businessfmspb128.mp3',
    image: './logos/biznesfm.jpg',
  },
];

export const frequencies = [87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109];
